title:               gavin's blog
url:                 https://loredunk.github.io/
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              g
  url:               loredunk.github.io/
  email:             chanlovelife@163.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
  - jekyll-paginate